name: Publish on Hugging Face Hub
on:
  push:
    branches:
      - huggingface
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with Hugging Face
      uses: nateraw/huggingface-sync-action@v0.0.4
      with:
        github_repo_id: iscc/iscc-sct
        huggingface_repo_id: iscc/iscc-sct
        repo_type: space
        space_sdk: gradio
        hf_token: ${{ secrets.HF_TOKEN }}
