name: Sync with Hugging Face Space
on:
  push:
    branches:
      - huggingface
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Sync with HF
      uses: alex-bene/huggingface-space-sync-action@v0.1
      with:
        github_repo_id: 'iscc/iscc-sct'
        github_branch: 'huggingface'
        yaml_header_path: 'space.yml'
        huggingface_repo_id: 'iscc/iscc-sct'
        hf_username: 'titusz'
        hf_token: ${{ secrets.HF_TOKEN }}
